version: '3.9'
services:
  
  localstack: 
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    volumes:
      - ./initialize_localstack.sh:/etc/localstack/init/ready.d/script.sh
  